# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='pos_or_neg',
            field=models.IntegerField(default=1),
        ),
    ]
