# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose_stock', '0002_auto_20160613_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pos_or_neg',
            new_name='flag_pn',
        ),
    ]
