# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_stock', '0006_auto_20160714_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeansdata',
            name='price_open',
            field=models.CharField(max_length=10),
        ),
    ]
