# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_stock', '0007_auto_20160714_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CStockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_cid_yes', models.CharField(max_length=300)),
                ('stock_cid_now', models.CharField(max_length=300)),
                ('cflag', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='KStockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_kid_yes', models.CharField(max_length=300)),
                ('stock_kid_now', models.CharField(max_length=300)),
                ('kflag', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VisitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('visit_time', models.DateTimeField()),
                ('visit_page', models.CharField(max_length=20)),
                ('visit_device', models.CharField(max_length=300)),
            ],
        ),
    ]
